apiVersion: v1
entries:
  agent:
  - apiVersion: v2
    appVersion: v0.0.1-nightly+23098e1
    created: "2023-08-31T04:35:06.751626442Z"
    description: A Helm cart for TIS Agent for Kubernetes.
    digest: 9ff580368e5b863514892e1fdcf546879c25b8d2faaae2c2fe67958a5ff6cdad
    name: agent
    urls:
    - agent-v0.0.1-nightly.tgz
    version: v0.0.1-nightly
generated: "2023-08-31T04:35:06.751218037Z"
