apiVersion: v1
entries:
  agent:
  - annotations:
      tetrate.io/system: "true"
    apiVersion: v2
    appVersion: v0.0.1-nightly+340dc69
    created: "2023-09-02T10:08:15.535757137Z"
    description: Helm cart for deploying TIS agent.
    digest: 32eb39b81b07ae81f64925bff6a2127a0564ad6853a1ca755f7d6aaca538aa7f
    name: agent
    urls:
    - agent-v0.0.1-nightly.tgz
    version: v0.0.1-nightly
generated: "2023-09-02T10:08:15.535394532Z"
